---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/pgsql/14/data"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath2
spec:
  storageClassName: hostpath2
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/pgsql/14/data"